In [2]:
from scipy import constants as cs

print(cs.liter)

0.001


In [4]:
import scipy
print(scipy.__version__)

1.7.1


In [5]:
from scipy import constants

print(constants.pi)

3.141592653589793


In [6]:
from scipy import constants

print(dir(constants))

['Avogadro', 'Boltzmann', 'Btu', 'Btu_IT', 'Btu_th', 'ConstantWarning', 'G', 'Julian_year', 'N_A', 'Planck', 'R', 'Rydberg', 'Stefan_Boltzmann', 'Wien', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_obsolete_constants', 'acre', 'alpha', 'angstrom', 'arcmin', 'arcminute', 'arcsec', 'arcsecond', 'astronomical_unit', 'atm', 'atmosphere', 'atomic_mass', 'atto', 'au', 'bar', 'barrel', 'bbl', 'blob', 'c', 'calorie', 'calorie_IT', 'calorie_th', 'carat', 'centi', 'codata', 'constants', 'convert_temperature', 'day', 'deci', 'degree', 'degree_Fahrenheit', 'deka', 'dyn', 'dyne', 'e', 'eV', 'electron_mass', 'electron_volt', 'elementary_charge', 'epsilon_0', 'erg', 'exa', 'exbi', 'femto', 'fermi', 'find', 'fine_structure', 'fluid_ounce', 'fluid_ounce_US', 'fluid_ounce_imp', 'foot', 'g', 'gallon', 'gallon_US', 'gallon_imp', 'gas_constant', 'gibi', 'giga', 'golden', 'golden_ratio', 'grain', 'gram', 'gravitational_con

In [9]:
print(constants.mmHg)

133.32236842105263


In [12]:
print(constants.kilo)

1000.0


In [13]:
#find the root of the equation x + cos(x)

from scipy.optimize import root
from math import cos

def eqn(x):
    return x + cos(x)

myroot = root(eqn,0)

print(myroot.x)

[-0.73908513]


In [14]:
print(myroot)

    fjac: array([[-1.]])
     fun: array([0.])
 message: 'The solution converged.'
    nfev: 9
     qtf: array([-2.66786593e-13])
       r: array([-1.67361202])
  status: 1
 success: True
       x: array([-0.73908513])


In [15]:
from scipy.optimize import minimize

def eqn(x):
    return x**2 + x + 2

mymin = minimize(eqn,0,method='BFGS')

print(mymin)

      fun: 1.75
 hess_inv: array([[0.50000001]])
      jac: array([0.])
  message: 'Optimization terminated successfully.'
     nfev: 8
      nit: 2
     njev: 4
   status: 0
  success: True
        x: array([-0.50000001])


In [22]:
from scipy.optimize import root
from math import cos

def eqn(x):
    return x + cos(x)

myroot=root(eqn,0)

print(myroot)

    fjac: array([[-1.]])
     fun: array([0.])
 message: 'The solution converged.'
    nfev: 9
     qtf: array([-2.66786593e-13])
       r: array([-1.67361202])
  status: 1
 success: True
       x: array([-0.73908513])


In [24]:
from scipy.optimize import root
from math import cos

def eqn(x):
    return x + cos(x)

myroot=root(eqn,0)

print(myroot.qtf)

[-2.66786593e-13]


In [25]:
import numpy as np
from scipy.sparse import csr_matrix

arr = np.array([0,0,0,0,0,1,1,0,2])

print(csr_matrix(arr))

  (0, 5)	1
  (0, 6)	1
  (0, 8)	2


In [1]:
import numpy as np
from scipy.sparse import csr_matrix

arr= np.array([[0,0,0],[0,0,1],[1,0,2]])

print(csr_matrix(arr).data)

[1 1 2]


In [6]:
# import numpy as np
from scipy.sparse import csr_matrix

arr=np.array([[0,0,0],[0,0,0],[1,0,2]])

print(csr_matrix(arr).count_nonzero())

2


In [7]:
#eliminate xeros
mat = csr_matrix(arr)
mat.eliminate_zeros()

print(mat)

  (2, 0)	1
  (2, 2)	2


In [8]:
mat.sum_duplicates()
print(mat)

  (2, 0)	1
  (2, 2)	2


In [11]:
#converting froim csr to csc with the tocsc()

newarr = mat.tocsc()
print(newarr)

  (2, 0)	1
  (2, 2)	2


In [12]:
print(mat.count_nonzero())

2


In [13]:
import numpy as np
from scipy.sparse.csgraph import connected_components
from scipy.sparse import csr_matrix

arr = np.array([
    [0,1,2],
    [1,0,0],
    [2,0,0]
])

newarr = csr_matrix(arr)

print(arr)

[[0 1 2]
 [1 0 0]
 [2 0 0]]


In [14]:
print(newarr)

  (0, 1)	1
  (0, 2)	2
  (1, 0)	1
  (2, 0)	2


In [15]:
print(connected_components(newarr))

(1, array([0, 0, 0], dtype=int32))


In [17]:
import numpy as np
from scipy.sparse.csgraph import dijkstra
from scipy.sparse import csr_matrix

arr = np.array([
    [0,1,2],
    [1,0,0],
    [2,0,0]
])

newarr= csr_matrix(arr)

print(dijkstra(newarr, return_predecessors=True,indices=0))

(array([0., 1., 2.]), array([-9999,     0,     0], dtype=int32))


In [18]:
#find the shortest path between all pairs of elements
import numpy as np
from scipy.sparse.csgraph import floyd_warshall
from scipy.sparse import csr_matrix

arr = np.array([
    [0,1,2],
    [1,0,0],
    [2,0,0]
])

newarr = csr_matrix(arr)

print(floyd_warshall(newarr, return_predecessors=True))

(array([[0., 1., 2.],
       [1., 0., 3.],
       [2., 3., 0.]]), array([[-9999,     0,     0],
       [    1, -9999,     0],
       [    2,     0, -9999]], dtype=int32))


In [19]:
#bellman ford
import numpy as np
from scipy.sparse.csgraph import bellman_ford
from scipy.sparse import csr_matrix

arr = np.array([
    [0,-1,2],
    [1,0,0],
    [2,0,0]
])

newarr = csr_matrix(arr)
print(bellman_ford(newarr, return_predecessors=True, indices=0))

(array([ 0., -1.,  2.]), array([-9999,     0,     0], dtype=int32))


In [22]:
'''The depth_first_order() method returns a depth first traversal from a node.

This function takes following arguments:

the graph.
the starting element to traverse graph from.'''

import numpy as np
from scipy.sparse.csgraph import depth_first_order as dfo
from scipy.sparse import csr_matrix as cm

arr=np.array([
    [0,1,0,1],
    [1,1,1,1],
    [2,1,1,0],
    [0,1,0,1]
])

newarr = cm(arr)
print(dfo(newarr,1))

(array([1, 0, 3, 2], dtype=int32), array([    1, -9999,     1,     0], dtype=int32))


In [23]:
import numpy as np
from scipy.sparse.csgraph import breadth_first_order
from scipy.sparse import csr_matrix

arr = np.array([
    [0,1,0,1],
    [1,1,1,1],
    [2,1,1,0],
    [0,1,0,1]
])

newarr= csr_matrix(arr)

print(breadth_first_order(newarr,1))

(array([1, 0, 2, 3], dtype=int32), array([    1, -9999,     1,     1], dtype=int32))


In [24]:
from scipy.interpolate import UnivariateSpline
import numpy as np

xs = np.arange(10)
ys = xs**2 + np.sin(xs) + 1

interp_func = UnivariateSpline(xs, ys)

In [25]:
from scipy import io
import numpy as np

arr = np.arange(10)

io.savemat('arr.mat',{"vec":arr})

In [26]:
from scipy import io
mydata = io.loadmat('arr.mat')

print(mydata)

{'__header__': b'MATLAB 5.0 MAT-file Platform: posix, Created on: Fri Jun 10 22:32:45 2022', '__version__': '1.0', '__globals__': [], 'vec': array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])}


In [29]:
import numpy as np
from scipy.stats import skew, kurtosis

v=np.random.normal(size=100)

print(skew(v))

0.18028430037037552


**STATISTICAL SIGNIFICANCE TEST**

In [1]:
#ttest
import numpy as np
from scipy.stats import ttest_ind

v1 = np.random.normal(size=100)
v2 = np.random.normal(size=100)

res = ttest_ind(v1,v2)

print(res)

Ttest_indResult(statistic=1.1936611964329742, pvalue=0.23403872388293093)


In [2]:
res = ttest_ind(v1,v2).pvalue

print(res)

0.23403872388293093


In [3]:
#KS-Test
import numpy as np
from scipy.stats import kstest

v= np.random.normal(size=100)

res = kstest(v, "norm")

print(res)

KstestResult(statistic=0.07099392592567333, pvalue=0.6679083644971895)


In [4]:
res1 = kstest(v,"norm").pvalue
print(res1)

0.6679083644971895


In [5]:
'''Statistical Description of Data
In order to see a summary of values in an array, we can use the describe() function.

It returns the following description:

number of observations (nobs)
minimum and maximum values = minmax
mean
variance
skewness
kurtosis'''

'Statistical Description of Data\nIn order to see a summary of values in an array, we can use the describe() function.\n\nIt returns the following description:\n\nnumber of observations (nobs)\nminimum and maximum values = minmax\nmean\nvariance\nskewness\nkurtosis'

In [6]:
import numpy as np
from scipy.stats import describe as ds

v = np.random.normal(size=100)
res = ds(v)

print(res)

DescribeResult(nobs=100, minmax=(-2.264013127778717, 1.9395603119732114), mean=-0.07530284935146626, variance=0.9339249253978381, skewness=-0.25207030118009677, kurtosis=-0.4546235449059779)


In [7]:
'''Normality Tests (Skewness and Kurtosis)
Normality tests are based on the skewness and kurtosis.

The normaltest() function returns p value for the null hypothesis:

"x comes from a normal distribution".

Skewness:
A measure of symmetry in data.

For normal distributions it is 0.

If it is negative, it means the data is skewed left.

If it is positive it means the data is skewed right.

Kurtosis:
A measure of whether the data is heavy or lightly tailed to a normal distribution.

Positive kurtosis means heavy tailed.

Negative kurtosis means lightly tailed.
'''

'Normality Tests (Skewness and Kurtosis)\nNormality tests are based on the skewness and kurtosis.\n\nThe normaltest() function returns p value for the null hypothesis:\n\n"x comes from a normal distribution".\n\nSkewness:\nA measure of symmetry in data.\n\nFor normal distributions it is 0.\n\nIf it is negative, it means the data is skewed left.\n\nIf it is positive it means the data is skewed right.\n\nKurtosis:\nA measure of whether the data is heavy or lightly tailed to a normal distribution.\n\nPositive kurtosis means heavy tailed.\n\nNegative kurtosis means lightly tailed.\n'

In [8]:
import numpy as np
from scipy.stats import skew, kurtosis

v= np.random.normal(size=100)

print(skew(v))
print(kurtosis(v))

0.4708524908449391
0.6251932846997965


In [9]:
#Find if the data comes from a normal distribution:
from scipy.stats import normaltest

v = np.random.normal(size=100)

print(normaltest(v))

NormaltestResult(statistic=0.6303719436274422, pvalue=0.7296531667277553)
